# Generated by Django 2.2.6 on 2019-10-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='default_availability',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='available', max_length=255),
        ),
        migrations.AlterField(
            model_name='suppliermarketavailability',
            name='availability',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='available', max_length=255),
        ),
    ]
