# Generated by Django 2.2.6 on 2019-10-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_saleschannel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Article'),
        ),
    ]
