# Generated by Django 2.2.6 on 2019-10-25 18:54

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    SupplyMarketAvailability = apps.get_model('catalog', 'SupplierMarketAvailability')
    db_alias = schema_editor.connection.alias
    SupplyMarketAvailability.objects.all().update(
        supplier=1,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191024_1910'),
    ]

    operations = [
        migrations.RunPython(
            forwards_func,
        ),
        migrations.AlterField(
            model_name='suppliermarketavailability',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Supplier'),
        ),
    ]
